/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Parcel.h"
/* Header for class com_example_jniparcel_DParcel */

#ifndef _Included_com_example_jniparcel_DParcel
#define _Included_com_example_jniparcel_DParcel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jniparcel_DParcel
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_jniparcel_DParcel_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniparcel_DParcel
 * Method:    nativeSetDataPosition
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_example_jniparcel_DParcel_nativeSetDataPosition
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_example_jniparcel_DParcel
 * Method:    nativeWriteInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_jniparcel_DParcel_nativeWriteInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_example_jniparcel_DParcel
 * Method:    nativeReadInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_jniparcel_DParcel_nativeReadInt
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
